apiVersion: apps/v1
kind: Deployment
metadata:
  name: #treetracker-microservice-name#
  labels:
    app: #treetracker-microservice-name#
spec:
  replicas: 2
  selector:
    matchLabels:
      app: #treetracker-microservice-name#
  template:
    metadata:
      labels:
        app: #treetracker-microservice-name#
    spec:
      containers:
      - name: #treetracker-microservice-name#
        image: greenstand/#treetracker-microservice-name#:VERSION
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: treetracker-api-database-connection
                key: db
          - name: DATABASE_SCHEMA
            value: #schema-name#
          - name: NODE_LOG_LEVEL
            value: trace
          - name: REMOTE_LOG_URL
            value: http://104.131.78.177:8000
